# This code is written by Team 6:
# Yi Ding, 839679
# Jianying Zhang, 799672
# Feifan Zhang, 807480
# Keren He, 865255
# Jinhang Li, 867117
---
- hosts: Nectarhost
  become: yes
  become_user: root
  tasks:
    - name: install git
      apt:
       name: git

    - name: install pip3
      apt: pkg=python3-pip
    - name: clone scraper to the instance
      git:
       repo: https://github.com/YD-UOM/COMP90024-A2-SweetHeart.git
       version: master
       dest: /home/ubuntu/sweetheart
       accept_hostkey: yes
      become: no
    - name: change database
      lineinfile: dest=/home/ubuntu/sweetheart/Harvester/config.py
                  regexp='^SERVER_ADDR '
                  line="SERVER_ADDR = 'http://admin:sweetheart@115.146.86.47:5986/'"
    - name: install python-package
      command: pip3 install {{ item }}
      with_items:
       - couchdb
       - tweepy
       - scikit-learn
       - numpy
       - nltk
       - pyshp
       - shapely
       - scipy
       - fiona
       - vaderSentiment
